local file_path = "/Users/alehzakharau/Documents/Defold/Projects/InfinityRace/data"
local file_name = "points"

local points
local index = 1
local time = 0

function init(self)
	local path = sys.get_save_file(file_path, file_name)
	 points = sys.load(path)
end

function update(self, dt)
	time = time + dt
	if time > .00001 then 
		time = 0
		local position = points[index]
		go.set_position(vmath.vector3(position.x, position.y, 0), "/go1")
		print(go.get_position("/go1"))
		index = index + 1
		if index > #points then index = 1 end
	end
end
